- name: print host
  hosts: all
  key_id: 8dae0259-1d22-47ef-a533-2cf7a81cb5c5
  tasks:
    - name: print parameter
      ansible.builtin.debug:
        msg: parameter - {{ lookup('aws_ssm', 'test1', region='us-east-1') }}